version: '3.8'

services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:2052"
      - "2053:2053"
    volumes:
      - ./src:/app/src
      - /etc/letsencrypt/live/giveawayproject.jettonetto.org:/etc/letsencrypt/live/giveawayproject.jettonetto.org:ro
      - /etc/letsencrypt/archive/giveawayproject.jettonetto.org:/etc/letsencrypt/archive/giveawayproject.jettonetto.org:ro
    environment:
      - NODE_ENV=development
