name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run with Docker Compose
      run: |
        docker compose down
        docker compose build --no-cache
        docker compose up -d

    - name: Clean up old images
      run: |
        docker image prune -f