name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment variables
      run: |
        echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env
        echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }}" >> .env
        echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}" >> .env
        echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }}" >> .env
        echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID }}" >> .env
        echo "VITE_APP_ID=${{ secrets.VITE_APP_ID }}" >> .env
        echo "VITE_MEASUREMENT_ID=${{ secrets.VITE_MEASUREMENT_ID }}" >> .env

    - name: Build and run with Docker Compose
      run: |
        docker compose down
        docker compose build --no-cache
        docker compose up -d
      env:
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
        VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
        VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
        VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
        VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
        VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}

    - name: Clean up old images
      run: |
        docker image prune -f